version: '3'
services:
    postgres:
        image: 'postgres:latest'
        ports:
            - 5432:5432
    redis:
        image: 'redis:latest'
        ports:
             - 3000:3000
    api:
        build:
            dockerfile: Dockerfile.dev
            context: .
            
        volumes:
            - /usr/app/node_modules
            - .:/usr/app
            
        environment:
            - REDIS_HOST=redis
            - REDIS_PORT=6379
            - PGUSER=postgres
            - PGHOST=postgres
            - PGDATABASE=postgres
            - PGPASSWORD=postgres_password
            - PGPORT=5432
    
        